### ISSUE TITLE
Does hidden step_factor make my simulation longer?

### ISSUE THREAD

**Issue by kevinPoliPoli** [OFFIS-mosaik/mosaik#11]
### Discussed in https://github.com/orgs/OFFIS-mosaik/discussions/9

<div type='discussions-op-text'>

<sup>Originally posted by **kevinPoliPoli** February  6, 2024</sup>
Hi everyone, I'm trying to use Mosaik with an FMU. Since then I have used the repo [Mosaik-fmi](https://gitlab.com/mosaik/components/mosaik-fmi/-/tree/master?ref_type=heads) but I recently discovered this [branch](https://gitlab.com/mosaik/components/mosaik-fmi/-/tree/import_fmi3_from_rep?ref_type=heads). I compared the master branch implementation with the last one and I obtain a strange behavior: specifically my FMU simulates an electric vehicle and outputs the level of charge after walking through a path. Comparing the same model inputs, using the last version of the linked branch the model outputs a significantly lower residual charge. Moreover, the simulation takes longer, in the first case takes 4 seconds to complete, and in the second one 57! So, maybe there is some hidden initialization parameter like the one in the main branch named step_factor which simulates more time? 

These are the initialization parameters:
### first repo
`
fmu_sim = world.start('FMI', step_size=1, step_factor=1,
                          stop_time=100000, work_dir=os.path.join(os.getcwd(), 'src/fmu/eGolf'), fmu_name='eGolf',
                          fmi_version='2', fmi_type='cs', logging_on=False, instance_name='eGolf')  
`
### second repo
`
fmu_sim = world.start('FMI3', step_size=1,
                          stop_time=100000, work_dir='/src/fmu/eGolf', fmu_name='eGolf',
                          fmi_version='2', fmi_type='cs', logging_on=False, instance_name='eGolf',
                          show_result=False, print_model=False, log_input=True)
`</div>

**Comment by eike** [comment]
This is not an issue in mosaik's core. The discussion was the right place for this; alternatively the mosaik-fmi project's issues on GitLab. Closing this.
